services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: crypt_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      # SSL sertifikati
      - /etc/letsencrypt/live/crypt-talk.online:/etc/letsencrypt/live/crypt-talk.online:ro
      - /etc/letsencrypt/archive/crypt-talk.online:/etc/letsencrypt/archive/crypt-talk.online:ro
    ports:
      - "${DOCKER_PORT_MAPPING}"
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: crypt_talk
      DB_USERNAME: crypt_user
      DB_PASSWORD: secret
    networks:
      - crypt_network
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: crypt_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: crypt_talk
      MYSQL_USER: crypt_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - crypt_network
networks:
  crypt_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
